### This code from [here](https://dacon.io/competitions/official/236179/codeshare/9437?page=1&dtype=recent).

#### EDA
1. 데이터 columns 확인
2. 결측치 확인
3. 레이블 분포 확인
4. 수치형 데이터 통계값
5. 범주형 데이터 통계값

In [1]:
import pandas as pd

In [2]:
train = pd.read_csv('../data/train.csv')
test = pd.read_csv('../data/test.csv')

In [3]:
train.info()
# 결측치는 없는 데이터
# user_id를 제외하고 object타입은 2개

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   user_id                            10000 non-null  object
 1   subscription_duration              10000 non-null  int64
 2   recent_login_time                  10000 non-null  int64
 3   average_login_time                 10000 non-null  float64
 4   average_time_per_learning_session  10000 non-null  float64
 5   monthly_active_learning_days       10000 non-null  int64
 6   total_completed_courses            10000 non-null  int64
 7   recent_learning_achievement        10000 non-null  float64
 8   abandoned_learning_sessions        10000 non-null  int64
 9   community_engagement_level         10000 non-null  int64
 10  preferred_difficulty_level         10000 non-null  object
 11  subscription_type                  10000 non-null  object
 12  customer_inquiry_history           10000 non-null  int64
 13  payment_pattern                    10000 non-null  int64
 14  target                             10000 non-null  int64
dtypes: float64(3), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
info = pd.read_csv('../data/data_info.csv')
info

,column,description
0,user_id,사용자의 고유 식별자
1,subscription_duration,사용자가 서비스에 가입한 기간 (월)
2,recent_login_time,사용자가 마지막으로 로그인한 시간 (일)
3,average_login_time,사용자의 일반적인 로그인 시간
4,average_time_per_learning_session,각 학습 세션에 소요된 평균 시간 (분)
5,monthly_active_learning_days,월간 활동적인 학습 일수
6,total_completed_courses,완료한 총 코스 수
7,recent_learning_achievement,최근 학습 성취도
8,abandoned_learning_sessions,중단된 학습 세션 수
9,community_engagement_level,커뮤니티 참여도
10,preferred_difficulty_level,선호하는 난이도
11,subscription_type,구독 유형
12,customer_inquiry_history,고객 문의 이력
13,payment_pattern,\n 사용자의 지난 3개월 간의 결제 패턴을 10진수로 표현한 값.\n ...
14,target,사용자가 다음 달에도 구독을 계속할지 (1) 또는 취소할지 (0)를 나타냅니다.

In [5]:
train.head()

,user_id,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,preferred_difficulty_level,subscription_type,customer_inquiry_history,payment_pattern,target
0,b919c29d,13,14,14.946163,8.427187,18,16,68.360455,3,4,Low,Basic,4,5,0
1,a0a60abb,16,18,18.453224,72.646087,16,13,97.567322,2,3,Medium,Basic,1,6,1
2,b9f171ae,22,1,16.195228,21.774492,13,14,94.358763,3,4,Medium,Premium,0,7,1
3,5dc0ba8b,1,19,17.628656,42.659066,19,18,70.153228,0,3,Low,Basic,1,0,1
4,65c83654,4,5,21.390656,30.744287,19,10,81.917908,2,4,Medium,Basic,3,0,1

In [6]:
train.shape, test.shape

((10000, 15), (10000, 14))

In [7]:
train.isnull().sum()

user_id                              0
subscription_duration                0
recent_login_time                    0
average_login_time                   0
average_time_per_learning_session    0
monthly_active_learning_days         0
total_completed_courses              0
recent_learning_achievement          0
abandoned_learning_sessions          0
community_engagement_level           0
preferred_difficulty_level           0
subscription_type                    0
customer_inquiry_history             0
payment_pattern                      0
target                               0
dtype: int64

In [8]:
test.isnull().sum()

user_id                              0
subscription_duration                0
recent_login_time                    0
average_login_time                   0
average_time_per_learning_session    0
monthly_active_learning_days         0
total_completed_courses              0
recent_learning_achievement          0
abandoned_learning_sessions          0
community_engagement_level           0
preferred_difficulty_level           0
subscription_type                    0
customer_inquiry_history             0
payment_pattern                      0
dtype: int64

In [9]:
# 타겟 비율 확인
print(train['target'].value_counts())
## unbalance 하네.
print(train['target'].value_counts(normalize=True))

target
1    6199
0    3801
Name: count, dtype: int64
target
1    0.6199
0    0.3801
Name: proportion, dtype: float64

In [10]:
# 수치형 변수 기초 통계
train.describe()

,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,customer_inquiry_history,payment_pattern,target
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,11.897400,15.013200,14.994076,54.917720,12.545400,12.227500,75.029513,3.043600,3.886100,2.010500,3.502900,0.619900
std,6.600896,8.362573,3.001869,56.024310,6.932239,3.634125,9.968529,1.755052,1.262175,1.420983,2.311261,0.485435
min,1.000000,1.000000,2.366189,0.011515,1.000000,1.000000,35.941755,0.000000,1.000000,0.000000,0.000000,0.000000
25%,6.000000,8.000000,13.025597,15.276611,7.000000,10.000000,68.278054,2.000000,3.000000,1.000000,1.000000,0.000000
50%,12.000000,15.000000,14.979228,37.578818,13.000000,12.000000,75.126061,3.000000,4.000000,2.000000,4.000000,1.000000
75%,18.000000,22.000000,16.995340,75.584200,19.000000,15.000000,81.718976,4.000000,5.000000,3.000000,6.000000,1.000000
max,23.000000,29.000000,26.998490,503.372616,24.000000,27.000000,112.643828,12.000000,5.000000,10.000000,7.000000,1.000000

In [11]:
# 범주형 변수 기초 통계
display(train.describe(include='O'))
display(test.describe(include='O'))

         user_id preferred_difficulty_level subscription_type
count      10000                      10000             10000
unique     10000                          3                 2
top     b919c29d                        Low             Basic
freq           1                       4992              5979

         user_id preferred_difficulty_level subscription_type
count      10000                      10000             10000
unique     10000                          3                 2
top     0001d6e9                     Medium             Basic
freq           1                       3372              5028

In [12]:
print(train['preferred_difficulty_level'].value_counts())
print(train['preferred_difficulty_level'].value_counts(normalize=True))

preferred_difficulty_level
Low       4992
Medium    3008
High      2000
Name: count, dtype: int64
preferred_difficulty_level
Low       0.4992
Medium    0.3008
High      0.2000
Name: proportion, dtype: float64

In [13]:
print(train['subscription_type'].value_counts())

subscription_type
Basic      5979
Premium    4021
Name: count, dtype: int64

### Data Preprocessing

In [14]:
# user_id 제거
train.pop('user_id')
test_user_id = test.pop('user_id')

# target 분리
target = train.pop('target')

In [15]:
# encoding
train = pd.get_dummies(train)
test = pd.get_dummies(test)

In [16]:
train.head(5)

,subscription_duration,recent_login_time,average_login_time,average_time_per_learning_session,monthly_active_learning_days,total_completed_courses,recent_learning_achievement,abandoned_learning_sessions,community_engagement_level,customer_inquiry_history,payment_pattern,preferred_difficulty_level_High,preferred_difficulty_level_Low,preferred_difficulty_level_Medium,subscription_type_Basic,subscription_type_Premium
0,13,14,14.946163,8.427187,18,16,68.360455,3,4,4,5,False,True,False,True,False
1,16,18,18.453224,72.646087,16,13,97.567322,2,3,1,6,False,False,True,True,False
2,22,1,16.195228,21.774492,13,14,94.358763,3,4,0,7,False,False,True,False,True
3,1,19,17.628656,42.659066,19,18,70.153228,0,3,1,0,False,True,False,True,False
4,4,5,21.390656,30.744287,19,10,81.917908,2,4,3,0,False,False,True,True,False

In [17]:
# split data to train_set and valid_set

from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(train, target, test_size=0.2, random_state=42)

## Random Forest Classifier

In [25]:
# 모델링 (random forest)
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train, y_train)
pred_rf = rf.predict(x_valid)

In [19]:
from sklearn.metrics import f1_score, log_loss

In [26]:
print("f1_score: ", f1_score(y_valid, pred_rf, average='macro'))
# print("log_loss: ", log_loss(y_valid, pred_rf)

f1_score:  0.5134116253141885

### Xgboost

In [51]:
# 모델링 (xgboost)
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=42, n_estimators=600, max_depth=3)
xgb.fit(x_train, y_train)
pred_xgb = xgb.predict(x_valid)

In [52]:
print("f1-score: ", f1_score(y_valid, pred_xgb, average='macro'))

f1-score:  0.5056409691731013

## Dicision Tree

In [60]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train, y_train)
pred_dt = dt.predict(x_valid)
print("f1-score: ", f1_score(y_valid, pred_dt, average='macro'))

f1-score:  0.5068098182783869

### Xgboost-DART

In [57]:
# import xgboost as xgb

# param = {'booster' : 'dart',
#          'max_depth' : 5,
#          'learning_rate': 0.05,
#          'objective': 'binary:logistic',
#          'sample_type': 'uniform',
#          'normalize_type': 'tree',
#          'rate_drop': 0.1,
#          'skip_drop': 0.5}
# num_round = 50
# bst = xgb.train(param, x_train, num_round)

TypeError: ('invalid cache item: DataFrame', [      subscription_duration  recent_login_time  average_login_time  \
9254                     11                  3           15.298435
1561                     14                 19           17.193117
1670                     13                 27           13.399272
6087                     19                  6           12.814237
6669                     20                  3           18.232309
...                     ...                ...                 ...
5734                      5                 15           16.348315
5191                     10                 24           20.926596
5390                     15                 12           16.692484
860                      16                 27           14.095176
7270                     18                 28           16.668378

      average_time_per_learning_session  monthly_active_learning_days  \
9254                          35.587179                             9
1561                         185.901568                            12
1670                           1.903421                            14
6087                          89.294899                             7
6669                          76.949024                            14
...                                 ...                           ...
5734                          48.808410                            23
5191                          41.718489                            17
5390                         100.130452                            22
860                           16.192716                             9
7270                          28.911117                             4

      total_completed_courses  recent_learning_achievement  \
9254                       15                    61.325364
1561                       14                    86.587523
1670                       15                    64.560131
6087                       10                    76.285842
6669                        9                    82.132995
...                       ...                          ...
5734                       14                    71.599465
5191                       11                    78.684889
5390                       21                   107.135153
860                        13                    55.206152
7270                       10                    81.867197

      abandoned_learning_sessions  community_engagement_level  \
9254                            4                           5
1561                            1                           5
1670                            3                           4
6087                            1                           4
6669                            4                           4
...                           ...                         ...
5734                            3                           3
5191                            6                           3
5390                            5                           5
860                             2                           4
7270                            3                           2

      customer_inquiry_history  payment_pattern  \
9254                         1                6
1561                         0                5
1670                         0                3
6087                         1                1
6669                         0                2
...                        ...              ...
5734                         3                0
5191                         0                1
5390                         1                6
860                          4                3
7270                         0                7

      preferred_difficulty_level_High  preferred_difficulty_level_Low  \
9254                            False                            True
1561                            False                            True
1670                            False                            True
6087                            False                            True
6669                            False                           False
...                               ...                             ...
5734                            False                           False
5191                            False                            True
5390                            False                            True
860                             False                           False
7270                            False                           False

      preferred_difficulty_level_Medium  subscription_type_Basic  \
9254                              False                     True
1561                              False                     True
1670                              False                    False
6087                              False                    False
6669                               True                    False
...                                 ...                      ...
5734                               True                     True
5191                              False                     True
5390                              False                    False
860                                True                    False
7270                               True                     True

      subscription_type_Premium
9254                      False
1561                      False
1670                       True
6087                       True
6669                       True
...                         ...
5734                      False
5191                      False
5390                       True
860                        True
7270                      False

[8000 rows x 16 columns]])

### 평가

### 제출

In [53]:
result = rf.predict(test)
submit = pd.DataFrame({
    'user_id': test_user_id,
    'target': result
})

In [54]:
submit.to_csv("rf-n_10.csv", index=False)